version: '3.8'

services:
    app_meta_builder:
        build:
          context: ..
          dockerfile: app.docker
        command: ["python3", "/apps/app_meta_builder.py", "--client_id", "app_meta_builder"]
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
          - /Volumes/AnnaX/Hive/merge:/merge

    app_image_hash_builder:
        build:
          context: ..
          dockerfile: app.docker
        command: ["python3", "/apps/app_image_hash_builder.py", "--client_id", "app_image_hash_builder"]
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
          - /Volumes/AnnaX/Hive/merge:/merge

    app_face_hash_builder:
        build:
          context: ..
          dockerfile: app.docker
        command: ["python3", "/apps/app_face_hash_builder.py", "--client_id", "app_face_hash_builder"]
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
          - /Volumes/AnnaX/Hive/merge:/merge

    app_meta_geo_build:
      build:
        context: ..
        dockerfile: app.docker
      command: [ "python3", "/apps/app_meta_geo_build.py"]
      volumes:
        - /Volumes/AnnaA/Hive/merge:/data
      environment:
        - TARGET_DIR=/data