version: '3.8'

services:
    app_take_into_meta:
        build:
          context: ..
          dockerfile: app.docker
        container_name: app_take_into_meta
        command: ["python3", "/apps/app_take_into_meta.py", "--client_id", "app_take_into_meta"]
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
          - /Volumes/AnnaX/Hive/merge:/merge