version: '3.8'

services:
    app_pad_sender:
        build:
          context: ..
          dockerfile: ../app_web.docker
        command: ["python3", "/apps/app_pad_sender.py", "--client_id", "app_pad_sender"]
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
        ports:
          - "8083:5000"