version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
    app_os_walker:
        build:
          context: ..
          dockerfile: app.docker
        container_name: app_os_walker
        command: ["python3", "/apps/app_os_walker.py"]
        depends_on:
          - rabbitmq
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
          - /Volumes/AnnaX/Hive/merge:/merge
    app_os_walker_batch:
        build:
          context: ..
          dockerfile: app.docker
        container_name: app_os_walker_batch
        command: [ "python3", "/apps/app_os_walker_batch.py", "--client_id", "app_os_walker_batch" ]
        volumes:
          - /Volumes/AnnaX/Hive/meta:/meta
          - /Volumes/AnnaX/Hive/storage:/source
        environment:
          - BATCH_SIZE_LIMIT_MB=500